name: curso_dart_udemy
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/GabrielRuanDM/curso_dart_udemy

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
